stages:
  - deploy

production_server_1:
  stage: deploy
  tags:
    - tag-hare-krishna-frontend-prod
  script:
    - rsync -hravz --exclude '.git' --exclude '.well-known' --exclude 'media' --exclude '.gitlab-ci.yml' --exclude '.env' . /var/www/erp-frontend/html
    - chown -R root:root /var/www/erp-frontend/html

production_server_2:
  stage: deploy
  tags:
    - tag-hare-krishna-frontend-sync-prod
  script:
    - rsync -hravz --exclude '.git' --exclude '.well-known' --exclude 'media' --exclude '.gitlab-ci.yml' --exclude '.env' . /var/www/hkisync/html
    - chown -R root:root /var/www/hkisync/html