stages:
  - deploy

production:
  tags:
    - tag-hare-krishna-backend-prod
  stage: deploy
  script:
    - rsync -hravz --exclude '.git' --exclude '.well-known' --exclude 'media'  --exclude '.env' . /var/www/erp-backend/html
    - chown -R root:root /var/www/erp-backend/html